default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: 5432
  database: <%= ENV["DATABASE_NAME"] %>
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASS"] %>
  sslmode: require
  gssencmode: disable
  connect_timeout: 5

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_TEST_NAME", "#{ENV["DATABASE_NAME"]}_test") %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] if ENV["DATABASE_URL"].present? %>
